[build]
  dockerfile = "Dockerfile"  # 使用 Dockerfile 构建

[[services]]
  internal_port = 80
  protocol = "tcp"
  
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "requests"
  
  [[services.ports]]
    port = 80  # 将 80 端口暴露为 HTTP 服务
